export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CONTACTS_LOADING = 'GET_CONTACTS_LOADING';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';

export const CONFIRM_CODE_LOADING = 'CONFIRM_CODE_LOADING';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_FAIL = 'CONFIRM_CODE_FAIL';

export const RESEND_CODE_LOADING = 'RESEND_CODE_LOADING';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const RESEND_CODE_FAIL = 'RESEND_CODE_FAIL';

export const RESET_PASSWORD_EMAIL_LOADING = 'RESET_PASSWORD_EMAIL_LOADING';
export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS';
export const RESET_PASSWORD_EMAIL_FAIL = 'RESET_PASSWORD_EMAIL_FAIL';

export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_COMPETITORS_LOADING = 'GET_COMPETITORS_LOADING';
export const GET_COMPETITORS_SUCCESS = 'GET_COMPETITORS_SUCCESS';
export const GET_COMPETITORS_FAIL = 'GET_COMPETITORS_FAIL';

export const GET_ALBUM_LOADING = 'GET_ALBUM_LOADING';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAIL = 'GET_ALBUM_FAIL';

export const CREATE_ALBUM_LOADING = 'CREATE_ALBUM_LOADING';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAIL = 'CREATE_ALBUM_FAIL';